language: php
php:
  - '7.0'
before_script: composer install
script: php ./build.php
deploy:
  provider: s3
  access_key_id: AKIAJITPCESODBMNJEMQ
  secret_access_key:
    secure: JdYgtngZ9MaL5IwkiBsKtJBqSDvLPEuRkc73KWUy/FSyTQ7sTvYi2/Z8gxSrVkUgFJxcAxSJpKke7ZILia/toJ+AY5R/KOoWNEM6Nc7CmVzhKZWRLmr9HuQT9S7Qa+3iq85nUjHup1P/NKiydxY0gywqAmgOXAiNo5AWdIRwkAY=
  bucket: markwilson.me
  local-dir: public
  acl: public_read
  region: eu-west-1
  on:
    repo: markwilson/markwilson.me
    branch: master
  skip_cleanup: true
