AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
  RecaptchaSecret:
    Type: String
  SendTo:
    Type: String
Globals:
  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
Resources:
  SendMessage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sendMessage/index.handler
      Runtime: nodejs12.x
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: "/"
            Method: post
      Environment:
        Variables:
          RECAPTCHA_SECRET:
            Ref: RecaptchaSecret
          INCLUDE_CORS_HEADERS: true
          SCORE_THRESHOLD: 0.5
          SEND_TO:
            Ref: SendTo
