name: PR close

on:
  pull_request:
    types: [closed]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup node (v18)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install app dependencies
        run: yarn install

      - name: Surge teardown
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: $(yarn bin surge) teardown --domain ${{ github.head_ref }}-markwilson.surge.sh
