name: Deploy to surge.sh

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: yarn install

      - name: Create production-ready build
        run: yarn build
        env:
          # This means the messages can't be tested from a PR on Surge
          REACT_APP_SEND_MESSAGE_URL: "http://localhost:3001/"

      - run: |
          ref="${github_ref////-}"
          echo $ref
          echo "::set-env name=SUBDOMAIN::$ref"
        env:
          github_ref: ${{ github.head_ref }}

      - name: Surge build
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: $(yarn bin surge) build --domain "$SUBDOMAIN-markwilson.surge.sh"

      - name: Comment on PR
        if: github.event.action == 'opened'
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `[${process.env.SUBDOMAIN}}-markwilson.surge.sh](https://${process.env.SUBDOMAIN}-markwilson.surge.sh)`
            })
