name: Deploy to surge.sh

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup node (v18)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup SUBDOMAIN environment variable
        run: |
          ref="${github_ref////-}"
          echo $ref
          echo "SUBDOMAIN=$ref" >> $GITHUB_ENV
        env:
          github_ref: ${{ github.head_ref }}

      - name: Install app dependencies
        run: yarn

      - name: Build static site
        run: yarn build

      - name: Run tests
        run: |
          yarn start:production-like-server &
          yarn test

      - name: Surge build
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: $(yarn bin surge) build --domain "${{ env.SUBDOMAIN }}-markwilson.surge.sh"

      - name: Comment on PR
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `[${{ env.SUBDOMAIN }}-markwilson.surge.sh](https://${{ env.SUBDOMAIN }}-markwilson.surge.sh)`
            })
