name: Deploy to markwilson.me

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: yarn install

      - name: Create production-ready build
        run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.26

      - name: Initialise Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Deploy to S3
        run: aws s3 sync --delete --acl public-read build s3://markwilson.me/

      - name: Get CloudFront distribution ID
        shell: bash
        id: get_cloudfront_distribution_id
        run: echo "::set-output name=id::$(terraform output cloudfront_distribution_id)"

      - name: Clear CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ steps.get_cloudfront_distribution_id.outputs.id }} --paths "/*"
