name: Deploy to markwilson.me

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  push:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v1

      - name: Setup node (v18)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install app dependencies
        run: yarn

      - name: Build static site
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./build/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main

      - name: Configure AWS credentials for Terraform S3 backend
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.7

      - name: Initialise Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
